### ISSUE TITLE
A question please

### ISSUE THREAD

**Issue by mengtalunhui** [lavender-RJ/Temporal-causal-representation-for-multivariate-power-load-forecasting#1]
I couldn't find the specific dataset mentioned in the project. Could you please provide more details on where I can access it? Additionally, I'd like to know if there were any preprocessing steps applied to the original dataset before using it in the experiments. If so, could you explain what those preprocessing steps were?

**Comment by lavender-RJ** [comment]
The dataset we used in our experiments can be found at the following link:
https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption

Regarding data preprocessing, we followed the methodology described in the following paper:
@article{aouad2022cnn,
title={A CNN-Sequence-to-Sequence network with attention for residential short-term load forecasting},
author={Aouad, Mosbah and Hajj, Hazem and Shaban, Khaled and Jabr, Rabih A and El-Hajj, Wassim},
journal={Electric Power Systems Research},
volume={211},
pages={108152},
year={2022},
publisher={Elsevier}
}

You can also use your own dataset if you wish. To do so, you would need to customize a class similar to Dataset_Custom in the dataloader file.

Hope this helps, and feel free to reach out if you have more questions!
